### ISSUE TITLE
RuntimeError: src/ngtpy.cpp

### ISSUE THREAD

**Issue by alvinhu** [knjcode/imgdupes#80]
running in python 3.9 get follow error:

$ imgdupes --recursive datasets phash 4
Building NGT index (dimension=64, num_proc=15)
Traceback (most recent call last):
  File "/home/huzhuolei/miniconda3/envs/imgdupes/bin/imgdupes", line 230, in <module>
    main()
  File "/home/huzhuolei/miniconda3/envs/imgdupes/bin/imgdupes", line 226, in main
    dedupe_images(args)
  File "/home/huzhuolei/miniconda3/envs/imgdupes/bin/imgdupes", line 94, in dedupe_images
    deduper.dedupe(args)
  File "/home/huzhuolei/miniconda3/envs/imgdupes/lib/python3.9/site-packages/common/imagededuper.py", line 172, in dedupe
    ngt_index.batch_insert(self.hashcache.hshs(), num_proc)
RuntimeError: src/ngtpy.cpp:

**Comment by amulikhov-mannequin** [comment]
have the same bug on python 3.8.12 and imgdupes 0.1.1

**Comment by alvinhu** [comment]
I have used the docker version instead, and it works smoothly. The docker file will install NGT, hnsw and Faiss automatically. We can copy the installation script out and run it at conda environment to make the correct dependency.
